# # DKDK this is for Section 4: Workflows & Events - Deep Dive
# # DKDK blocked for Section 5: jobs Artifacts & Outputs
# name: Events Demo 1
# # events: activity types & filters
# # on: [push, workflow_dispatch]
# on:
#   # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
#   pull_request:
#     # activity types
#     types:
#       - opened
#     branches:
#       - master
#       - 'dev-*'
#       - 'feat/**'
#   workflow_dispatch:
#   push:
#     # filters
#     branches:
#       - master
#       - 'dev-*'     # dev-new dev-this-is-new: * does not include slash (/)
#       - 'feat/**'   # feat/new feat/new/button: ** includes slash (/)
#     # paths:
#     paths-ignore:
#       - '.github/workflows/*'
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Output event data
#         run: echo "${{ toJSON(github.event) }}"
#       - name: Get code
#         uses: actions/checkout@v3
#       - name: Install dependencies
#         run: npm ci
#       - name: Test code
#         run: npm run test
#       - name: Build code
#         run: npm run build
#       - name: Deploy project
#         run: echo "Deploying..."