# calling other workflow in conjunction with this workflow
name: Reusable Deploy
# DKDK calling other workflow
on: workflow_call
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: echo "Deplying & uploading..."
